stages:
  - vetting
  - lint
  - tests
  - deploy

cache:
  key: "$CI_PROJECT_NAME"
  untracked: true
  paths:
    - "$GOPATH/pkg/mod"


variables:
  CI_IMAGE: "golangci/golangci-lint"
  GOMODULE: "on"


golangci-lint:
  image: $CI_IMAGE
  stage: lint
  script:
    - make precommit

test:golang:
  image: golang:1.13
  stage: tests
  script:
    - go env
    - go version
    - go mod vendor
    - make test-unit


test:integration:
  image: docker
  services:
    - docker:dind
  before_script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  stage: tests
  script:
    - make test-integration

staging:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=otus-ci-staging --api-key=$HEROKU_API_KEY
  environment:
    name: Staging
    url: https://otus-ci-staging.herokuapp.com/
  only:
    - master

production:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=otus-ci --api-key=$HEROKU_API_KEY
  environment:
    name: Production
    url: https://otus-ci.herokuapp.com/
  only:
    - tags
  when: manual
