stages:
  - check

cache:
  key: "$CI_PROJECT_NAME"
  untracked: true
  paths:
    - "$GOPATH/pkg/mod"

variables:
  CI_IMAGE: "golangci/golangci-lint"
  GOMODULE: "on"

golangci-lint:
  image: $CI_IMAGE
  stage: check
  script:
    - make precommit

test-golang:
  image: golang:1.13
  stage: check
  script:
    - go env
    - go version
    - go mod vendor
    - make test-unit

test-integration:
  image: docker
  services:
    - docker:dind
  before_script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  stage: check
  script:
    - make test-integration
